version: '3.8'

services:
  drupal:
    build: .
    container_name: drupal_custom
    ports:
      - "8080:80"
    volumes:
      - ./sites:/var/www/html/sites
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
