name: Drupal CI/CD

on:
  push:
    branches: [main]   # Runs only when code is pushed to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Log in to ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS \
            --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 4: Build Docker image
      - name: Build Docker Image
        run: |
          IMAGE_NAME=drupal-app
          docker build -t $IMAGE_NAME:${{ github.sha }} .

      # Step 5: Tag & Push to ECR
      - name: Tag & Push Docker Image
        run: |
          AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          IMAGE_NAME=drupal-app
          ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_NAME

          echo "Tagging image with commit SHA and latest..."
          docker tag $IMAGE_NAME:${{ github.sha }} $ECR_URI:${{ github.sha }}
          docker tag $IMAGE_NAME:${{ github.sha }} $ECR_URI:latest

          echo "Pushing both tags to ECR..."
          docker push $ECR_URI:${{ github.sha }}
          docker push $ECR_URI:latest

          echo "✅ Image pushed: $ECR_URI"
